main: PKGBOB450.Main
name: BOB450-SMP
version: '1.0'
description: A test plugin
author: BOB450
website: thegamearchive.net
commands:
  helpsmp:
    description: A help command to get players aqainted with the server.
    usage: /helpsmp
    permission: Main.an
  heal:
    description: Heals the player to full
    usage: /heal
    permission: Main.op
  rules:
    description: Displays server rules
    usage: /rules
    permission: Main.an
permissions:
  Main.an:
    description: Allows anyone to use
    default: true
  Main.op:
    description: only operators can use
    default: op